### ISSUE TITLE
打包完成后如何部署

### ISSUE THREAD

**Issue by lishuminjames** [fmfe/vue-genesis-micro#10]
打包完成后，该怎么样部署到服务器呢，是否能用常规的部署方式

**Comment by lzxb** [comment]
常规的是指什么？纯粹的静态资源文件吗？这样要取决于你是否需要SSR

**Comment by lishuminjames** [comment]
就是静态文件部署，应该是属于CSR




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月19日(星期六) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
常规的是指什么？纯粹的静态资源文件吗？这样要取决于你是否需要SSR
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
那就把静态资源，直接丢到服务器上即可。首屏的html估计你在编译的时候也需要生成一下，可以看下这个：
https://fmfe.github.io/genesis-docs/blog/2020-05-25.html#%E6%8B%93%E5%B1%95

**Comment by lishuminjames** [comment]
这一段扩展的代码是写到哪里，


还有，这里打包出来server文件里面有index.html,这里有三个文件，是否都要生成csr的index.html首屏文件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午11:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
那就把静态资源，直接丢到服务器上即可。首屏的html估计你在编译的时候也需要生成一下，可以看下这个：
 https://fmfe.github.io/genesis-docs/blog/2020-05-25.html#%E6%8B%93%E5%B1%95
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
肯定是写到编译的时候啊，它就是帮你使用server的index.html生成CSR渲染需要的html，否则你是不知道html需要引入哪些css和js的

**Comment by lishuminjames** [comment]
这个我看到了，你这里有两份源码



两份的配置文件配置都不一样，还是说这个功能时一样的，都是获取子应用的配置
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
肯定是写到编译的时候啊，它就是帮你使用server的index.html生成CSR渲染需要的html，否则你是不知道html需要引入哪些css和js的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
那你可以试试

**Comment by lishuminjames** [comment]
试着改了这几个参数，打包出来的js、css路径都不对




是优先读内置webpack里面的配置吗？
是否只能这里改





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午12:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
那你可以试试
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
截图看看

**Comment by lishuminjames** [comment]
上面一封邮件里有相关的截图，还有个问题，如果是各个子模块要交互，比如传递参数（token），远程加载文档里面没看到相关东西，又或者共用Vuex里面的某些数据（比如登录用户信息），在不同的子系统里面就没法共用了，只能用浏览器的缓存了吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
截图看看
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
我看不到你说的截图。Genesis是无法共享的，但是Genesis2.0可以共享。你这个是新的项目吗？

**Comment by lishuminjames** [comment]
![image](https://user-images.githubusercontent.com/26424075/155688097-aa92e5d0-d6fc-48cf-b1da-af85cb14310b.png)

**Comment by lzxb** [comment]
这个路径没有毛病。没明白你说的路径错误是什么

**Comment by bitem-cn** [comment]
> 打包完成后，该怎么样部署到服务器呢，是否能用常规的部署方式

可以用docker部署，编写对应的dockerfile制作镜像，然后用docker run 启动即可

**Comment by lishuminjames** [comment]
和index.html同一级并没有ssr_about 文件夹，只有css和js，打包出来应该是./css才能访问到静态资源




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfe/vue-genesis-micro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午5:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fmfe/vue-genesis-micro] 打包完成后如何部署 (Issue #10)





 
这个路径没有毛病。没明白你说的路径错误是什么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lzxb** [comment]
HTML使用的是绝对路径，不会是相对路径的。
