### ISSUE TITLE
独立启动子服务的问题？测试环境：Windows 10+VS Code

### ISSUE THREAD

**Issue by bitem-cn** [fmfe/vue-genesis-micro#11]
```
import { RouterMode } from 'vue-router';
import { Router } from '@fmfe/genesis-app';

interface State {
    routerMode?: RouterMode;
}

export const createRouter = (state: State) => {
    return new Router({
        // Resolve an issue where sub-services cannot be started 
        mode: state.routerMode || 'history',
        // mode: state?.routerMode || 'history',
        routes: [
            {
                path: '/',
                component: () =>
                    import(
                        './views/home.vue'
                    ).then((m) => m.default)
            }
        ]
    });
};
```
原有代码无法启动Server
![image](https://user-images.githubusercontent.com/96805327/154881215-ef3f33f7-acc2-444f-82be-da4e4305b82e.png)
修改后Server能够启动
![image](https://user-images.githubusercontent.com/96805327/154881192-87860baf-b8fc-4603-8849-2ec25279b190.png)

**Comment by liuminahcn** [comment]
`import { RouterMode } from 'vue-router';
import { Router } from '@fmfe/genesis-app';

interface State {
routerMode?: RouterMode;
}

export const createRouter = (state: State) => {
return new Router({
// Resolve an issue where sub-services cannot be started
mode: state.routerMode || 'history',
// mode: state?.routerMode || 'history',
routes: [
{
path: '/',
component: () =>
import(
'./views/home.vue'
).then((m) => m.default)
}
]
});
};`

**Comment by lzxb** [comment]
这个是js的边界问题，修改一下即可，非核心库的问题。
最近在升级webpack5，如果是新的项目，建议直接使用2.x，
到时候推荐使用模块联邦，而不是远程组件。
https://github.com/fmfe/genesis/tree/feat-webpack5
可以看下这个例子：
https://github.com/fmfe/genesis/tree/feat-webpack5/examples
