### ISSUE TITLE
@fmfe/genesis-app/route 在使用 base 的模式下 会有问题

### ISSUE THREAD

**Issue by freeozyl80** [fmfe/vue-genesis-micro#5]
![image](https://user-images.githubusercontent.com/8967606/103991463-a8f97b80-51cd-11eb-87c9-2394a9422cb4.png)

**Comment by lzxb** [comment]
我试试。

**Comment by freeozyl80** [comment]
自己手动改了下，大概思路：

1. __genesisAppRouter 存放 baseUrl
2.  自定义Router 的 replace 和 push 的时候，对 baseUrl 作 split
3.  history 的 push 和 replace 的时候，对baseUrl 作添加

**Comment by lzxb** [comment]
@fmfe/genesis-app 更新到93修复了，这个问题

具体可以看：
https://github.com/fmfe/genesis/commit/7f5a6fa797c83c0060a4b70bf3f0f7f42d1a6826

**Comment by lzxb** [comment]
__genesisAppRouter 是全局的，不应该设置全局的base

**Comment by lzxb** [comment]
这里有个问题就是无法单个服务使用base，必须要全部的服务使用base

**Comment by lzxb** [comment]
否则这路由同步的时候，就会出现url不一致，混乱的bug。

**Comment by lzxb** [comment]
你要是实现了支持单个服务的base，可以给我提个PR过来。我想了一下，确实是可以实现。

**Comment by freeozyl80** [comment]
设置全局的 base 就是为了 不让 全部的 服务使用base

**Comment by freeozyl80** [comment]
> 你要是实现了支持单个服务的base，可以给我提个PR过来。我想了一下，确实是可以实现。

好的

**Comment by lzxb** [comment]
如果不同的服务，设置不同的base，这一块的逻辑也需要思考一下。

**Comment by freeozyl80** [comment]
> 如果不同的服务，设置不同的base，这一块的逻辑也需要思考一下。

这个初步感觉没法解决，你要是 子服务 不是单独被 起的服务 而是 作为 微服务被加载，你的 host 和 baseUrl 就一样没有 存在的意义了

**Comment by lzxb** [comment]
想了一下，还是有办法解决的。触发变更的路由，同步的目标路由时，判断一下触发变更的路由有base，则给同步的路由补上base，同步的目标路由有base时，则把url的base去掉。
