### ISSUE TITLE
npm run dev/build 都报错提示找不到no such file or directory

### ISSUE THREAD

**Issue by ltgan1121** [fmfe/vue-genesis-micro#6]
(node:2369) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/Users/gbd/Desktop/project/vue-genesis-micro-master/examples/ssr-common/dist/ssr-common/src/entry-client.ts'

**Comment by lzxb** [comment]
截图看下是否有这个文件？可能在window系统下有些兼容性问题

**Comment by ltgan1121** [comment]
这目录一开始就没有的，我试着加目录文件进去，dan但会默认先rm这目录下的东西，我是mac电脑
![image](https://user-images.githubusercontent.com/12512833/105347787-5767dc80-5c22-11eb-8a7b-918a0068013b.png)

**Comment by lzxb** [comment]
你的系统是什么？

**Comment by lzxb** [comment]
是不是文件的权限有问题？我也是mac，刚试了一下是正常的。node版本多少？

**Comment by ltgan1121** [comment]
mac os 10.14.6，node v10.10.0，文件权限全放开了

**Comment by lzxb** [comment]
代码都是刚拉的吗？

**Comment by lzxb** [comment]
我切换到node10.10版本，确实有这个bug。我看一下为啥导致的

**Comment by ltgan1121** [comment]
是的，今晚拉下来的，你能看到图么

![image](https://user-images.githubusercontent.com/12512833/105348419-453a6e00-5c23-11eb-8884-0f6c08e4e996.png)

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/105348477-5d11f200-5c23-11eb-9b18-3ca16bddf84b.png)

这个第三方库写入报错了。

**Comment by lzxb** [comment]
![image](https://user-images.githubusercontent.com/8424643/105348567-7ca91a80-5c23-11eb-8424-bbe2c09a44c6.png)


![image](https://user-images.githubusercontent.com/8424643/105348979-05c05180-5c24-11eb-97b5-69325f276760.png)


创建目录的node api报错了。

**Comment by ltgan1121** [comment]
那我更新node 版本再试一下

**Comment by lzxb** [comment]
👌，建议版本都在12.x以上。

**Comment by lzxb** [comment]
😺，问个问题，你是从哪里了解到Genesis的?

**Comment by ltgan1121** [comment]
我有个问题想请教一下， 如果我不弄node服务，只做CSR，比如多个前端vue项目的微前端架构，是否能支持？

**Comment by ltgan1121** [comment]
由于项目需要，在了解多个vue项目如何相互独立、解耦，最终又可是一个整体，在思考这个架构时网上搜索的

**Comment by ltgan1121** [comment]
genesis好像并不普遍，我得多实践一下哇，我一开始以为是VUE团队的产品

**Comment by lzxb** [comment]
CSR的当然也是支持的。你把远程组件的原理搞明白就可以了。在编译阶段，每个项目都输出对应的json入口就好了。

**Comment by lzxb** [comment]
你可以看下这篇CSR的文章。
https://fmfe.github.io/genesis-docs/blog/2020-05-25.html#%E4%BF%AE%E6%94%B9%E7%BC%96%E8%AF%91%E4%BB%A3%E7%A0%81

**Comment by lzxb** [comment]
我其实也一直想寻求Vue官方的帮助，但是没理我(🥺)。可以看下这个网站，https://www.followme.com/ 我们已经大量的应用了，前前后后十几个服务构成。

**Comment by lzxb** [comment]
我们只是在服务端首屏的时候，会采用SSR渲染，但是客户端切换路由的时候，都是采用CSR渲染。

**Comment by ltgan1121** [comment]
好的，谢谢，我先消化一下，单独看看CSR这个先

**Comment by ltgan1121** [comment]
csr的例子，有简单针对普通的vue项目的样例么？

**Comment by lzxb** [comment]
没有这样的例子，你只要编译的阶段，输出json文件就好了。然后远程组件调用的时候，请求到这个json的内容就可以了。

**Comment by ltgan1121** [comment]
嗯呐，原理知道，就是你的样例都是基于vue3，用的ts，有些细节不一样，我这边用的是vue2.6，那我自己再看看，谢啦

**Comment by lzxb** [comment]
目前都是vue2，不是vue3。目前webpack5和vue3都还不太成熟。

**Comment by ltgan1121** [comment]
大神，我做了一个csr的demo了，可是我想请问下，
就是关于子服务vue项目的路由管理和基础结构这块，
1、一定要用@fmfe/genesis-app的Router么，用旧项目的vue-router不行么？
2、入口文件一定是entry-client.ts，然后用@fmfe/genesis-core的ClientOptions、@fmfe/genesis-app的createClientApp么

**Comment by lzxb** [comment]
第一点：是的，一定要使用`@fmfe/genesis-app`，否则会有bug。如果两个服务都使用历史模式，就会有毛病。
第二点：这个不是必须的，你可以看下它的源码，这样可以更好的了解它是怎么工作的

https://github.com/fmfe/genesis/blob/master/packages/genesis-app/src/create-app.ts
