### ISSUE TITLE
@fmfe/genesis-app/src/index

### ISSUE THREAD

**Issue by yuedefeng** [fmfe/vue-genesis-micro#7]
npm ERR! Invalid package name "@fmfe/genesis-app/src/index": name can only contain URL-friendly characters

**Comment by yuedefeng** [comment]
![image](https://user-images.githubusercontent.com/8114016/124925751-58a19000-e02f-11eb-94db-74e8be96e172.png)

**Comment by lzxb** [comment]
The package name should be "@fmfe/genesis-app"

**Comment by lzxb** [comment]
Fixed. Pull the latest code
