### ISSUE TITLE
请问一下。全局数据状态是如何管理呢？还有跨子服务间的通信有什么解决方案？

### ISSUE THREAD

**Issue by macroswang** [fmfe/vue-genesis-micro#8]
请问一下。全局数据状态是如何管理呢？还有跨子服务间的通信有什么解决方案？

**Comment by lzxb** [comment]
全局的状态管理，可以挂载到window上，给各个子服务中的store访问，适合当前用户登录状态之类的。
跨子服务通信，可以使用全局的自定义事件，或者其它的事件订阅系统实现也都可以。

**Comment by macroswang** [comment]
hi lzxb 感谢你的回复！
不知有没有这方面的DEMO可以提供一下吗？我发现genesis方面的参考资料太少了！

**Comment by lzxb** [comment]
Genesis 的定为只是一个库作为使用，更为深度的解决方案，还需要自己想想。
