### ISSUE TITLE
How to pass context to the root instance of vue

### ISSUE THREAD

**Issue by sunzhengya** [fmfe/vue-genesis-micro#9]
作者你好，请教一个问题：我在 NUXT 项目中使用 remote-view 的 serverFetch来做SSR，报错 '[remote-view] Need to pass context to the root instance of vue' ，看文档也有说明，但是 How to pass context to the root instance of vue  in Nuxt Project？

**Comment by lzxb** [comment]
你看下远程组件的源码：https://github.com/fmfe/genesis/blob/master/packages/genesis-remote/src/index.ts
这个不支持在nuxt中使用，但是你可以把源码修改一下，适配一下nuxt
